name: Bug report
description: Report a problem with the Pulse Guard Pack reusable workflow.
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Clear, concise description of the issue and the expected behavior.
      placeholder: The job failed with...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal workflow or PR that reproduces the issue.
      placeholder: |
        1) ...
        2) ...
  - type: input
    id: ref
    attributes:
      label: Version/reference
      description: v1 or a specific commit SHA of the reusable workflow.
      placeholder: v1 or a commit SHA
  - type: dropdown
    id: runner
    attributes:
      label: Runner OS
      options: [ubuntu-latest, windows-latest, macos-latest]
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Redact any sensitive data before pasting.
