name: Feature request
description: Suggest an improvement to the Pulse Guard Pack.
labels: [enhancement]
title: "[Feat]: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Context
      description: What problem would the feature solve?
      placeholder: The current guard makes it hard to...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      placeholder: Add an option/flag to...
  - type: textarea
    id: whyuseful
    attributes:
      label: Why useful
      placeholder: This helps teams by...
  - type: input
    id: refs
    attributes:
      label: References
      placeholder: Links to related issues, PRs, or docs
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight
      options:
        - label: I verified this is not already solved by existing options or docs.
        - label: I can help test a prototype if needed.
